YourLib/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('searchResult/<int:options>/<str:key>', views.searchView, name="search"),
    path('likes/<str:id>/<str:ttl>/', views.likeViews, name="likes"),
    path('bookmark/<str:id>/<str:ttl>/', views.bookmarkViews, name="bookmark"),
    path('search/', views.search, name="search"),
    path('likeList/', views.likeList, name="likeList"),
    path('bookmarkList/', views.bookmarkList, name="bookmarkList"),
    path('unlike/<str:id>', views.unlike, name="unlike"),
    path('unbook/<str:id>', views.unbook, name="unbook"),
]

main/models.py
from django.db import models

# Create your models here.

class LikesModel(models.Model):
    movieId = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    year = models.CharField(max_length=255)
    plotStr = models.CharField(max_length=255, null=True)
    poster = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.title
    
    def get_unlike_url(self):
        return "/unlike/" + self.movieId

class BookmarkModel(models.Model):
    movieId = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    year = models.CharField(max_length=255)
    plotStr = models.CharField(max_length=255, null=True)
    poster = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.title

    def get_unbook_url(self):
        return "/unbook/" + self.movieId

main/views.py
from django.shortcuts import render
import requests
from django.http import JsonResponse
import json
from .models import LikesModel, BookmarkModel
from django.shortcuts import redirect


def home(request):
    return render(request, 'main/home.html')

def likeViews (request, id, ttl):
    year = request.GET.get('year')
    plot = request.GET.get('plot')
    poster = request.GET.get('poster')
    objNow = LikesModel.objects.filter(movieId = id)
    if(objNow.exists()):
        objNow.delete()
    else:
        newObj = LikesModel.objects.create(movieId = id, title = ttl, year = year, plotStr = plot, poster = poster)
        newObj.save()
    
    updateObj = searchView(request, 1, id)

    return updateObj

def bookmarkViews (request, id, ttl):
    objNow = BookmarkModel.objects.filter(movieId = id)
    year = request.GET.get('year')
    plot = request.GET.get('plot')
    poster = request.GET.get('poster')
    if(objNow.exists()):
        objNow.delete()
    else:
        newObj = BookmarkModel.objects.create(movieId = id, title = ttl, year = year, plotStr = plot, poster = poster)
        newObj.save()
    
    updateObj = searchView(request, 1, id)

    return updateObj


def searchView(request, options, key):
    result=0
    objLiked=""
    objBookmarked=""
    if (options == 2):
        result = requests.get('http://www.omdbapi.com/?apikey=e1f98568&t=' + key).json()
        objLiked = LikesModel.objects.filter(movieId=result['imdbID'])
        objBookmarked = BookmarkModel.objects.filter(movieId=result['imdbID'])
    else:
        result = requests.get('http://www.omdbapi.com/?apikey=e1f98568&i=' + key).json()
        objLiked = LikesModel.objects.filter(movieId=key)
        objBookmarked = BookmarkModel.objects.filter(movieId=key)

    #Search Model dan jika ada

    if(objLiked.exists()):
        result ['isLiked'] = 'True'
    else:
        result ['isLiked'] = 'False'

    if(objBookmarked.exists()):
        result ['isBookmarked'] = 'True'
    else:
        result ['isBookmarked'] = 'False'
    
    return JsonResponse(result)

def search(request):
    return render(request, 'main/search.html')

def likeList(request):
    allLikes = LikesModel.objects.all()
    return render(request, 'main/likeList.html', {'allLikes': allLikes})

def bookmarkList(request):
    allBookmark = BookmarkModel.objects.all()
    return render(request, 'main/bookmarkList.html', {'allBookmark': allBookmark})    

def unlike(request, id):
    LikesModel.objects.filter(movieId=id).delete()
    return redirect('/likeList/')

def unbook(request, id):
    BookmarkModel.objects.filter(movieId=id).delete()
    return redirect('/bookmarkList/')

main/templates/main/bookmarkList.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Yourlib, Where the Movies Assemble</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet"> 
<link rel="stylesheet" href="{% static 'css/yourLib.css' %}">
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="/">YourLib</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-nav mr-auto">
      <a class="nav-link" href="{% url 'main:likeList' %}">Like List<span class="sr-only">(current)</span></a>
      <a class="nav-link" href="{% url 'main:bookmarkList' %}">Bookmark List<span class="sr-only">(current)</span></a>
    </div>
  </div>
</nav>

<div class="container justify-content-center text-center titleList">
  <h1 class="display-4 judul">Bookmark List</h1>
  <p class="lead">This is where you can see what the users bookmark</p>
</div>

<div class="row padding">
    {%for movie in allBookmark%}
    <div class="col-md-3 kartu">
      <span name="dataId" style="display:none">{{ movie.get_movie_id }}</span>
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{{movie.poster}}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{movie}}({{movie.year}})</h5>
          <p class="card-text">{{movie.plotStr}}</p>
          <a type="submit" class="btn btn-outline-success my-2 my-sm-0 btn-primary active" id="likesBtn" href="{{movie.get_unbook_url}}">Unbook</a>
        </div>
      </div>
  </div>
    {%endfor%}
</div>

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static 'js/yourlib.js' %}"></script>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Yourlib, Where the Movies Assemble</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/yourLib.css' %}">
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="/">YourLib</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-nav mr-auto">
      <a class="nav-link" href="{% url 'main:likeList' %}">Like List<span class="sr-only">(current)</span></a>
      <a class="nav-link" href="{% url 'main:bookmarkList' %}">Bookmark List<span class="sr-only">(current)</span></a>
    </div>

    <select class="form-control searchType" id="searchType">
      <option value="1">IMDb ID</option>
      <option value="2">title</option>
    </select>

    <!-- <form class="form-inline my-2 my-lg-0"></form> -->
    <input class="form-control mr-sm-2" type="text" id="searchIn" placeholder="Search" aria-label="Search">
    <input type="button" class="btn btn-outline-success my-2 my-sm-0 btn-primary" id="searchBtn" value="Go"
      data-target="#searchBox" onclick="location.href='#searchBox';">
    <!-- </form> -->
  </div>
</nav>

<div id="results" class="resultBox"></div>

<section>
  <div id="Carousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#Carousel" data-slide-to="0" class="active"></li>
      <li data-target="#Carousel" data-slide-to="1"></li>
      <li data-target="#Carousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <img class="d-block w-100 h-50 dark" src="{% static 'img/AIW.jpg' %}" alt="First Slide">
        <div class="carousel-caption">
          <h3>Avengers : Infinity War</h3>
          <p>The Avengers must stop Thanos, an intergalactic warlord, <br>from getting his hands on all the infinity
            stones. <br>However, Thanos is prepared to go to any lengths to carry out his insane plan.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100 h-50 dark" src="{% static 'img/Wanda Vision.jpg' %}" alt="Second Slide">
        <div class="carousel-caption">
          <h3>Wanda Vision</h3>
          <p>Three weeks after the events of Avengers: Endgame (2019),<br>
            Wanda Maximoff and Vision are living an idyllic suburban life in the town of Westview, New Jersey, trying to
            conceal their true natures.<br>
            As they begin to enter new decades and encounter television tropes, the couple suspects that things are not
            as they seem.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100 h-50 dark" src="{% static 'img/queen gambit.jpg' %}" alt="Third Slide">
        <div class="carousel-caption">
          <h3>Queen's Gambit</h3>
          <p>The Queen's Gambit follows the life of an orphan chess prodigy, Elizabeth Harmon,<br>
            during her quest to become the world's greatest chess player while struggling with emotional problems and
            drug and alcohol dependency. <br>
            The title of the series refers to a chess opening of the same name.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="introduction ">
  <div class="jumbotron jumbotron-fluid ">
    <div class="container justify-content-center text-center">
      <h1 class="display-4 judul">Welcome to YourLib!</h1>
      <p class="lead">YourLib is a platform where you can search, likes, and bookmarks your favourite movie.<br>
        Love watching movies? or want to search one? Just try us :D
      </p>
      <hr>
    </div>

  </div>
</section>

<div class="parallax">
  <div class="text-center justify-content-center container-fluid quotes">
    <h1 class="display-4 judul judulPutih">“The most honest form of filmmaking is to make a film for yourself.”</h1>
    <p class="lead putih">- Peter Jackson</p>
  </div>
</div>



<div class="jumbotron jumbotron-fluid" id="searchBox">
  <div class="container justify-content-center text-center">
    <h1 class="display-4 judul">Start Searching!</h1>
    <p class="lead">fill the form in Your Navbar to start searching
    </p>
    <hr>
  </div>
  <div id="results"></div>
</div>

<section id="list">
  <div class="row justify-content-center text-center">
    <h1 class="judul display-4">Check People's Favorite !</h1>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-6 justify-content-center text-center">
      <h2>People Liked This One !</h2>
      <br>
      <a class="btn btn-outline-success my-2 my-sm-0 btn-primary" href="{% url 'main:likeList'%}" role="button">Go to
        Like List...</a>
    </div>
    <div class="col-md-6 justify-content-center text-center">
      <h2>People Bookmarked This One !</h2>
      <br>
      <a class="btn btn-outline-success my-2 my-sm-0 btn-primary" href="{% url 'main:bookmarkList'%}" role="button">Go
        to Bookmark List...</a>
    </div>
  </div>

</section>

<footer>
  <div class="container-fluid padding footer">
    <div class="col-lg-12 text-center">
      <h5 class="display-3 judulPutih">About Me</h5>
      <h3 class="display-5 putih">a student who still learning
      </h3>
    </div>
    <div class="row padding">
      <div class="col-12 social padding d-flex justify-content-center">
        <a href="https://www.facebook.com/pwigunarta" class="fa fa-facebook" target="_blank"></a>
        <a href="https://www.instagram.com/putu.wig/" class="fa fa-instagram" target="_blank"></a>
        <a href="https://www.linkedin.com/in/putu-wigunarta-16ba57192/" class="fa fa-linkedin" target="_blank"></a>
      </div>
    </div>
  </div>
</footer>


<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static 'js/yourlib.js' %}"></script>
{% endblock content %}

main/templates/main/likeList.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Yourlib, Where the Movies Assemble</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/yourLib.css' %}">
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="/">YourLib</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-nav mr-auto">
      <a class="nav-link" href="{% url 'main:likeList' %}">Like List<span class="sr-only">(current)</span></a>
      <a class="nav-link" href="{% url 'main:bookmarkList' %}">Bookmark List<span class="sr-only">(current)</span></a>
    </div>
  </div>
</nav>

<div class="container justify-content-center text-center titleList">
  <h1 class="display-4 judul">Like List</h1>
  <p class="lead">This is where you can see what the users Like</p>
</div>

<div class="row padding">
  {%for movie in allLikes%}
  <div class="col-md-3 kartu">
      <span name="dataId" style="display:none">{{ movie.get_movie_id }}</span>
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{{movie.poster}}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{movie}}({{movie.year}})</h5>
          <p class="card-text">{{movie.plotStr}}</p>
          <a type="submit" class="btn btn-outline-success my-2 my-sm-0 btn-primary active" id="likesBtn" href="{{movie.get_unlike_url}}">Unike</a>
        </div>
      </div>
  </div>
  {%endfor%}
</div>

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static 'js/likeList.js' %}"></script>
{% endblock content %}

main/templates/main/search.html
<div id="results"></div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>